controllers/HomeController.php
<?php

namespace app\controllers;

use \DateTime;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use app\models\LoginForm;
use app\models\ExportForm;
use yii\data\ActiveDataProvider;

class HomeController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
            'class' => AccessControl::className(),
            'rules' => [
                    [
                        'actions' => ['login'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : NULL,
            ],
        ];
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

controllers/ProfileController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\User;

class ProfileController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
            'class' => AccessControl::className(),
            'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
    	$user = Yii::$app->user->identity;
        return $this->render('index', [ 'model' => $user ]);
    }

    public function actionUpdate()
    {
    	$model = Yii::$app->user->identity;
        $model->scenario = User::SCENARIO_UPDATE_PROFILE;

        if ($model->load(Yii::$app->request->post())) {

            if(!empty($model->_password)) {
                $model->setPassword($model->_password);
            }
            if($model->save()) {
            	return $this->redirect(['index']);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);

$this->registerCssFile('/js/jquery-ui/1.11.4/jquery-ui.min.css');
$this->registerCssFile('/js/jquery-multiselect/jquery.multiselect.css');

$this->registerJsFile('/js/jquery-1.11.3.min.js');
$this->registerJsFile('/js/jquery-ui/1.11.4/jquery-ui.min.js');
$this->registerJsFile('/js/jquery-multiselect/jquery.multiselect.js');

$isAdmin = !Yii::$app->user->isGuest && Yii::$app->user->identity->getRole() === "administrator";
$isAuthenticated = !Yii::$app->user->isGuest;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Time Management System',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            [
                'label' => 'Management',
                'items' => [
                    [
                        'label' => 'Users',
                        'url' => ['/admin/user/index'],
                        'visible' => $isAdmin
                    ],
                ],
                'visible' => $isAdmin
            ],
            ['label' => 'Profile', 'url' => ['/profile/index'], 'visible' => $isAuthenticated],
            $isAuthenticated ?
                [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/home/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ] :
                ['label' => 'Login', 'url' => ['/home/login']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; TheITFox <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>